name: CI

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install requirements
        run: pip install black==20.8b1 flake8 isort
      - name: Black check formatting
        run: black --check .
      - name: Check imports using isort
        run: isort --check-only .
      - name: Flake8 linting
        run: flake8 .

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Setup conda
        run: |
          $CONDA/bin/conda install -c pytorch faiss-gpu pip -y
          $CONDA/bin/conda activate base
      - name: Install pip packages
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -v tests/
