name: CI

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Debug
        run: ls
      - name: Install requirements
        run: pip install black==20.8b1 flake8 isort
      - name: Black check formatting
        run: black --verbose --check .
      - name: Check imports using isort
        run: isort -v --check-only .
      - name: Flake8 linting
        run: flake8 -v --ignore=E203 .

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Debug
        run: ls
      - name: Setup conda
        run: |
          $CONDA/bin/conda install python=3.7
          $CONDA/bin/conda install -c pytorch faiss-cpu pip -y
      - name: Install pip packages
        run: $CONDA/bin/pip install -r requirements.txt
      - name: Run tests
        run: $CONDA/bin/python -m pytest -v tests/
